# Generated by Django 5.2.14 on 2026-05-23 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='state',
            field=models.BooleanField(choices=[(True, 'Done'), (False, 'Not done')]),
        ),
    ]
