# Generated by Django 5.2.14 on 2026-05-24 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0002_alter_todo_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='is_done',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='todo',
            name='state',
            field=models.BooleanField(choices=[(True, 'Done'), (False, 'Not done')], default=False),
        ),
    ]
